<?xml version="1.0"?>
<robot name="roscontrol" xmlns:xacro="http://ros.org/wiki/xacro"> 
 
    <xacro:property name="BASE_X" value="0.4"/>
    <xacro:property name="BASE_Y" value="0.6"/>
    <xacro:property name="BASE_Z" value="0.3"/>

    <xacro:property name="RIGHT_BASE_X" value="0.1"/>
    <xacro:property name="RIGHT_BASE_Y" value="0.8"/>
    <xacro:property name="RIGHT_BASE_Z" value="0.1"/>
   
    <xacro:property name="LEFT_BASE_X" value="0.1"/>
    <xacro:property name="LEFT_BASE_Y" value="0.8"/>
    <xacro:property name="LEFT_BASE_Z" value="0.1"/> 
   
    <xacro:property name="LEFT_BASE_LEG_1_X" value="0.05"/>
    <xacro:property name="LEFT_BASE_LEG_1_Y" value="0.05"/>
    <xacro:property name="LEFT_BASE_LEG_1_Z" value="0.6"/> 

    <xacro:property name="LEFT_BASE_LEG_2_X" value="0.05"/>
    <xacro:property name="LEFT_BASE_LEG_2_Y" value="0.05"/>
    <xacro:property name="LEFT_BASE_LEG_2_Z" value="0.6"/> 

    <xacro:property name="LEFT_BASE_LEG_3_X" value="0.05"/>
    <xacro:property name="LEFT_BASE_LEG_3_Y" value="0.05"/>
    <xacro:property name="LEFT_BASE_LEG_3_Z" value="0.6"/> 

    <xacro:property name="RIGHT_BASE_LEG_1_X" value="0.05"/>
    <xacro:property name="RIGHT_BASE_LEG_1_Y" value="0.05"/>
    <xacro:property name="RIGHT_BASE_LEG_1_Z" value="0.6"/> 

    <xacro:property name="RIGHT_BASE_LEG_2_X" value="0.05"/>
    <xacro:property name="RIGHT_BASE_LEG_2_Y" value="0.05"/>
    <xacro:property name="RIGHT_BASE_LEG_2_Z" value="0.6"/> 

    <xacro:property name="RIGHT_BASE_LEG_3_X" value="0.05"/>
    <xacro:property name="RIGHT_BASE_LEG_3_Y" value="0.05"/>
    <xacro:property name="RIGHT_BASE_LEG_3_Z" value="0.6"/>
    
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="uncolor">
        <color rgba="0 0.8 0 1"/>
    </material>
    
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    
    <link name="base_link"> 
        <visual>
            <geometry>
                <box size="${BASE_X} ${BASE_Y} ${BASE_Z}"/>
            </geometry>
        </visual>
    </link>

    <link name="right_base_link">
        <visual>
            <geometry>
                <box size="${RIGHT_BASE_X} ${RIGHT_BASE_Y} ${RIGHT_BASE_Z}"/>
            </geometry>
            <material name="blue"/>
        </visual> 
    </link>

    <joint name="right_base_joint" type="continuous">
        <parent link="base_link"/>
        <child  link="right_base_link"/>
        <origin rpy="0 0 0" xyz="${BASE_X / 2 + RIGHT_BASE_X / 2} 0 0"/>
    </joint>

    <link name="left_base_link">
        <visual>
            <geometry>
                <box size="${LEFT_BASE_X} ${LEFT_BASE_Y} ${LEFT_BASE_Z}"/>
            </geometry>
            <material name="blue"/>
        </visual> 
    </link>

    <joint name="left_base_joint" type="continuous">
        <parent link="base_link"/>
        <child  link="left_base_link"/>
        <origin rpy="0 0 0" xyz="-${BASE_X / 2 + LEFT_BASE_X / 2} 0 0"/>
    </joint>

    <link name="left_base_leg_1_link">
        <visual>
            <geometry>
                <box size="${LEFT_BASE_LEG_1_X} ${LEFT_BASE_LEG_1_Y} ${LEFT_BASE_LEG_1_Z}"/>
            </geometry>
            <material name="white"/>
            <origin rpy="0 0 0" xyz="-${LEFT_BASE_X / 2 + LEFT_BASE_LEG_1_X / 2} 0 -0.2"/>
        </visual> 
    </link>

    <joint name="left_base_leg_1_joint" type="continuous">
        <parent link="left_base_link"/>
        <child  link="left_base_leg_1_link"/>
        <origin rpy="0 0 0" xyz="0 0.3 0"/>
    </joint>
    
    <link name="left_leg_1_bottom_link">
        <visual>
            <geometry>
                <box size="${LEFT_BASE_LEG_1_X} ${LEFT_BASE_LEG_1_Y} ${LEFT_BASE_LEG_1_Z}"/>
            </geometry>
            <material name="uncolor"/>
            <origin rpy="0 0 0" xyz="-${LEFT_BASE_X / 2 + LEFT_BASE_LEG_1_X / 2} 0 -0.2"/>
        </visual> 
    </link>

    <joint name="left_leg_1_bottom_joint" type="continuous">
        <parent link="left_base_leg_1_link"/>
        <child  link="left_leg_1_bottom_link"/>
        <origin rpy="0 0 0" xyz="0 0 -0.5"/>
    </joint>

    <link name="left_base_leg_2_link">
        <visual>
            <geometry>
                <box size="${LEFT_BASE_LEG_2_X} ${LEFT_BASE_LEG_2_Y} ${LEFT_BASE_LEG_2_Z}"/>
            </geometry>
            <material name="white"/>
            <origin rpy="0 0 0" xyz="-${LEFT_BASE_X / 2 + LEFT_BASE_LEG_2_X / 2} 0 -0.2"/>
        </visual> 
    </link>

    <joint name="left_base_leg_2_joint" type="continuous">
        <parent link="left_base_link"/>
        <child  link="left_base_leg_2_link"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>


    <link name="left_base_leg_3_link">
        <visual>
            <geometry>
                <box size="${LEFT_BASE_LEG_3_X} ${LEFT_BASE_LEG_3_Y} ${LEFT_BASE_LEG_3_Z}"/>
            </geometry>
            <material name="white"/>
            <origin rpy="0 0 0" xyz="-${LEFT_BASE_X / 2 + LEFT_BASE_LEG_3_X / 2} 0 -0.2"/>
        </visual> 
    </link>

    <joint name="left_base_leg_3_joint" type="continuous">
        <parent link="left_base_link"/>
        <child  link="left_base_leg_3_link"/>
        <origin rpy="0 0 0" xyz="0 -0.3 0"/>
    </joint>

    <link name="right_base_leg_1_link">
        <visual>
            <geometry>
                <box size="${RIGHT_BASE_LEG_1_X} ${RIGHT_BASE_LEG_1_Y} ${RIGHT_BASE_LEG_1_Z}"/>
            </geometry>
            <material name="white"/>
            <origin rpy="0 0 0" xyz="${RIGHT_BASE_X / 2 + RIGHT_BASE_LEG_1_X / 2} 0 -0.2"/>
        </visual> 
    </link>

    <joint name="right_base_leg_1_joint" type="continuous">
        <parent link="right_base_link"/>
        <child  link="right_base_leg_1_link"/>
        <origin rpy="0 0 0" xyz="0 0.3 0"/>
    </joint>

    <link name="right_base_leg_2_link">
        <visual>
            <geometry>
                <box size="${RIGHT_BASE_LEG_2_X} ${RIGHT_BASE_LEG_2_Y} ${RIGHT_BASE_LEG_2_Z}"/>
            </geometry>
            <material name="white"/>
            <origin rpy="0 0 0" xyz="${RIGHT_BASE_X / 2 + RIGHT_BASE_LEG_2_X / 2} 0 -0.2"/>
        </visual> 
    </link>

    <joint name="right_base_leg_2_joint" type="continuous">
        <parent link="right_base_link"/>
        <child  link="right_base_leg_2_link"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>


    <link name="right_base_leg_3_link">
        <visual>
            <geometry>
                <box size="${RIGHT_BASE_LEG_3_X} ${RIGHT_BASE_LEG_3_Y} ${RIGHT_BASE_LEG_3_Z}"/>
            </geometry>
            <material name="white"/>
            <origin rpy="0 0 0" xyz="${RIGHT_BASE_X / 2 + RIGHT_BASE_LEG_3_X / 2} 0 -0.2"/>
        </visual> 
    </link>

    <joint name="right_base_leg_3_joint" type="continuous">
        <parent link="right_base_link"/>
        <child  link="right_base_leg_3_link"/>
        <origin rpy="0 0 0" xyz="0 -0.3 0"/>
    </joint>
</robot>
